# Generated by Django 4.1.7 on 2023-06-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SharesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epic", models.CharField(default="", max_length=10)),
                ("shares", models.FloatField(default=0.0)),
                ("purchase_price", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["epic"],
            },
        ),
        migrations.CreateModel(
            name="UsersModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=100)),
                ("lastname", models.CharField(blank=True, max_length=100)),
                ("ftse_id", models.ManyToManyField(to="comps.sharesmodel")),
            ],
        ),
    ]
