# Generated by Django 4.1.7 on 2023-05-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comp_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epic", models.CharField(default="", max_length=10)),
                ("holding", models.IntegerField()),
                ("total_cost", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Memebers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comp.comp_model",
                    ),
                ),
            ],
        ),
    ]
