# Generated by Django 4.1.7 on 2023-05-19 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comp_model",
            old_name="total_cost",
            new_name="start_price",
        ),
    ]
