# Generated by Django 4.1.7 on 2023-05-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comp", "0002_rename_total_cost_comp_model_start_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="memebers",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="memebers",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
