# Generated by Django 4.1.7 on 2023-05-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comp", "0003_memebers_first_name_memebers_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comp_model",
            name="holding",
            field=models.FloatField(),
        ),
    ]
