# Generated by Django 4.1.7 on 2023-05-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comp", "0004_alter_comp_model_holding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memebers",
            name="member",
        ),
        migrations.AddField(
            model_name="memebers",
            name="member",
            field=models.ManyToManyField(to="comp.comp_model"),
        ),
    ]
